name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Expo EAS iOS Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Expo CLI and EAS CLI
      - name: Install Expo CLI and EAS CLI
        run: npm install -g expo-cli eas-cli

      # Step 4: Authenticate with Expo
      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      # Step 5: Run EAS Build for iOS
      - name: Build iOS App
        run: eas build --platform ios --non-interactive

      # Step 6: Fetch the Build Artifact
      - name: Download Build Artifact
        run: |
          mkdir -p build-output
          eas build:fetch --platform ios --non-interactive --output ./build-output/app.ipa

      # Step 7: Upload .ipa to GitHub Releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build-output/app.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
